### ISSUE TITLE
i am using  rtmp://14.141.165.149:14142/live/livestream/101791541211 url . its not working. can you please help me

### ISSUE THREAD

**Issue by SuryaChundawat** [PonnamKarthik/RTMP-Exo-Player-Demp#1]

**Comment by ponnamkarthik** [comment]
@SuryaChundawat  have you tested your URL is playing in other media players like VLC

**Comment by SuryaChundawat** [comment]
@PonnamKarthik  yes i have tested it in VLC media player its working

**Comment by PonnamKarthik** [comment]
Can you post the error logs 

i tried playing the above URL in VLCand it's not working

**Comment by SuryaChundawat** [comment]
I got below in logcat

E/ExoPlayerImplInternal: Source error.
                                                                                              net.butterflytv.rtmp_client.RtmpClient$RtmpIOException
                                                                                                  at net.butterflytv.rtmp_client.RtmpClient.open(RtmpClient.java:53)
                                                                                                  at com.google.android.exoplayer2.ext.rtmp.RtmpDataSource.open(RtmpDataSource.java:57)
                                                                                                  at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:692)
                                                                                                  at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
                                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                                  at java.lang.Thread.run(Thread.java:818)

**Comment by PonnamKarthik** [comment]
Hai @SuryaChundawat I have tested the URL using the demo app and its working fine 

can you please check your network connection

**Comment by ponnamkarthik** [comment]
@SuryaChundawat the issue is with link it is playing sometimes and giving error sometimes 


please verify your link

**Comment by SuryaChundawat** [comment]
@PonnamKarthik  I'm trying the same with vlc media player sdk it's working but Exo Player i'm not getting proper output

**Comment by ponnamkarthik** [comment]
Please refer the issue [ant-media/LibRtmp-Client-for-Android#52.](https://github.com/ant-media/LibRtmp-Client-for-Android/issues/52)
